version: '3.9'
services:
  userService:
    container_name: user_app_container1
    image: user_app_image1
    build: ./
    networks:
      - mynetwork1
    ports:
      - 8091:8091
    depends_on:
      - mongoService

  mongoService:
    container_name: mongo_container1
    image: mongo:3.6
    networks:
      - mynetwork1
    ports:
      - 27017:27017

networks:
  mynetwork1:
      driver: bridge